version: '3'

services:
  ni:
    image: ethereum-node-inspector
    container_name: ethereum-node-inspector
    ports:
      - 8080:8080
    environment:
      - RPC_ENDPOINT=http://192.168.65.1:8545

  unit:
    image: golang:1.8
    volumes:
      - .:/usr/src/myapp
      - ~/projects/go:/go
    working_dir: /usr/src/myapp
    command: bash -c "go get -d -v -t && go test --cover -v ./... && go build -v -o index"
